### ISSUE TITLE
Needs edit & delete functionality

### ISSUE THREAD

**Issue by Kav91** [newrelic/nr1-neon#2]
## Desired Behaviour

Provide delete capabilities

## Additional context

Users can't delete their dashboards

**Comment by fwcombs** [comment]
Not only does there need to be a dashboard delete.  There also needs to be a way to edit or delete rows and columns due to typo's etc ...

**Comment by glitton** [comment]
Delete functionality added.  Working on editing rows and columns, text.

**Comment by amit-y** [comment]
Thanks to @glitton, you can now delete dashboards. I'm closing this issue and moving @fwcombs request to it its own issue.
