### ISSUE TITLE
On empty state, provide a more friendly look ahead for the setup

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-neon#25]
Currently, the empty state of the application doesn't provide appropriate documentation to highlight that an Alert hooks needs to be configured against. 

- [ ] On empty state, execute a NRQL query to determine in Alert events exist in NRDB
- [ ] If no, surface a message explaining that the webhook needs to be setup and linking to a document in the Neon repository related to https://github.com/newrelic/nr1-neon/issues/24
- [ ] If yes, confirm that there is data available for setting up alerts

**Comment by glitton** [comment]
This capability already exists and I will ad documentation to ensure that users understand this.

**Comment by glitton** [comment]
FYI, I added an empty state as well as documentation so this piece should be resolved.
