### ISSUE TITLE
Showing Green when there is an Open Alert condition

### ISSUE THREAD

**Issue by abdulrahman7818** [newrelic/nr1-neon#8]
I have installed Neon Nerdpack but it’s showing green when there is an open alert condition. Is this normal.
I just included transaction board and alert policy  related to transaction - FYI.
![Neon Nerdpack](https://user-images.githubusercontent.com/58011984/69442585-757e3800-0d12-11ea-945b-a1fe9dda11f5.png)
![Query Alert Condition](https://user-images.githubusercontent.com/58011984/69442587-757e3800-0d12-11ea-9f68-3d9372ff6552.png)

**Comment by amit-y** [comment]
Hi @abdulrahman7818! From the query you ran, it appears you're looking for data from a day ago. When Neon queries data, it use the time range specified in the timepicker, located at the top right corner of the page. The default for the timepicker is 'last 30 mins.' When it queries data, and does not receive any records for that time range, it assumes all is well. If you want it to query from beyond the default, switch the time picker to an earlier time.
![screenshot of timepicker](https://user-images.githubusercontent.com/6021115/69447405-4e703800-0d0b-11ea-9a52-722ed89c9889.png)

**Comment by abdulrahman7818** [comment]
Hi Amit,

Thank you for your response and sorry for the delay in reply.

I tried, but even then it's showing green. Could you please verify and let me know if you want me to attach the samples.

**Comment by amit-y** [comment]
Hi @abdulrahman7818,

The next time you see this happening, can you run this query, and verify that you're getting the right results from the query, please?

```
SELECT latest(current_state), latest(incident_id) FROM alert WHERE policy_name IN ('POLICY_NAME') FACET policy_name, condition_name SINCE 30 minutes ago LIMIT MAX
```

I'm assuming you're sending the notifications to the `alert` event, based on your screenshot. Also, replace `POLICY_NAME` with the name of the alert policy. You can also list multiple policy names within the parenthesis, comma separated, and with each policy name surrounded with single quotes.

If you're seeing a different output in the query you ran than what you're seeing in Neon, could you put in a ticket through New Relic support, please? I may need additional information to debug, and I'd rather not have your data show up here.

You can put in the ticket here: https://support.newrelic.com/new-ticket
